# -*- coding: utf-8 -*-
"""CP2K_on_googleColab_H2Os.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1crXm9zqFF-UVfnRkfeP6UsOscNF_B2XV

# **CP2K on GoogleColab**

*by Mahmoud Moqadam & Thibault Michel Joseph Tubiana*

## 1. Preparation (_installation and file creation_)
"""

#Information on CPU available
!lscpu

#CONDA IS NOT PRESENT. You have to instal it first.
!wget https://repo.continuum.io/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh && bash Miniconda3-4.5.4-Linux-x86_64.sh -bfp /usr/local
#Add the new install conda package in path.
import sys
sys.path.append('/usr/local/lib/python3.6/site-packages')
#Install all dependancies.
!conda install -y -c conda-forge -c eumetsat cp2k fftw3 blas=2.5=mkl 
# Doing some things
!cd /content/
!mkdir -p cp2k
!cd cp2k
!pwd
!ls

"""## 2. Running CP2K"""

# create a empty "out" file
!touch out 
# Run CP2K
!cp2k.sopt -o out FILE_NAME.inp & tail -f out

"""###3. Analysis Archive and download the results."""

# Plot temperature, potential, and conserved quantity profiles 
from scipy import *
import numpy as np  
import matplotlib.pyplot as plt

data = np.loadtxt('FILE_NAME-1.ener')

plt.plot(data[:,0], data[:,3], 'r.') 
plt.show()

!cd /content/cp2k/
!zip FILE_NAME_results.zip FILE_NAME* 
!rm FILE_NAME-* 
from google.colab import files
files.download('FILE_NAME_results.zip')